- hosts: localhost
  connection: local
  tags: always
  vars_files:
    - vars/main.yaml
  pre_tasks:
    - name: Update Cache (Ubuntu)
      tags: always
      become: true
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install Updates (Ubuntu)
      tags: always
      become: true
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Ansible community.general
      become_user: "{{ user }}"
      ansible.builtin.shell:
        cmd: "ansible-galaxy collection install community.general"
  roles:
    - base
    - appearance
    - development
    - virtualization
