- hosts: localhost
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: update cache
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: install updates
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
  roles:
    - base
