- hosts: localhost
  connection: local
  tags: always
  vars_files:
    - vars/main.yaml
  pre_tasks:
    - name: Update Cache (Ubuntu)
      tags: always
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install Updates (Ubuntu)
      tags: always
      become: true
      apt:
        upgrade: yes
      when: ansible_distribution == "Ubuntu"
  roles:
    - appearance
    - development
    - virtualization
