- name: install packages
  tags: packages
  become: true
  apt:
    name: 
      - virtualbox
      - qemu-kvm
      - libvirt-daemon
      - libvirt-clients
      - bridge-utils
      - virtinst
      - cpu-checker
      - virt-manager
    state: latest
  when: ansible_distribution == "Ubuntu"
