- name: install packages
  tags: packages
  become: true
  apt:
    name: 
      - git
      - zsh
      - curl
      - ninja-build
      - gettext
      - cmake
      - unzip
      - build-essential
      - stow
      - silversearcher-ag
      - fd-find
      - python3-psutil
      - xclip
      - terminator
      - ripgrep
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install asdf
  become_user: "{{ user }}"
  tags: asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: $HOME/.asdf
    version: v0.14.0 
