- name: install packages
  tags: packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - zsh
      - curl
      - ninja-build
      - gettext
      - cmake
      - unzip
      - build-essential
      - stow
      - silversearcher-ag
      - fd-find
      - python3-psutil
      - xclip
      - terminator
      - ripgrep
      - btop
      - jq
      - nmap
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install asdf
  become_user: "{{ user }}"
  tags: asdf
  ansible.builtin.git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: $HOME/.asdf
    version: v0.14.0

- name: Get Obsidian package
  become_user: "{{ user }}"
  ansible.builtin.get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ version.obsidian }}/obsidian-{{ version.obsidian }}-amd64.deb"
    dest: $HOME/obsidian.deb

- name: Install Obsidian
  become: true
  ansible.builtin.apt:
    deb: /home/{{ user }}/obsidian.deb
