- name: install packages
  apt:
    name: 
      - git
      - zsh
      - curl
      - vim
      - ninja-build
      - gettext
      - cmake
      - unzip
      - build-essential
      - stow
    state: latest
  when: ansible_distribution == "Ubuntu"
