- name: Check if oh-my-zsh directory exists
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/
  register: ohmyzsh

- name: Check zsh spaceship theme simbolic link exists
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.stat:
    path: $HOME/.oh-my-zsh/themes/spaceship.zsh-theme
  register: theme_sym

- name: Install oh-my-zsh
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.shell:
    cmd: "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash"
  when: ohmyzsh.stat.isdir is not defined 

- name: Install spaceship theme
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: /home/neftales/.oh-my-zsh/themes/spaceship-prompt/
    depth: 1

- name: Create a simbolic link to zsh theme
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.file:
    src: /home/neftales/.oh-my-zsh/themes/spaceship-prompt/spaceship.zsh-theme
    dest: /home/neftales/.oh-my-zsh/themes/spaceship.zsh-theme
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  when: theme_sym.stat.islnk is not defined

- name: Check zsh simbolic link exists
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.stat:
    path: $HOME/.zshrc
  register: sym

- name: Delete default .zshrc file
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.file:
    path: $HOME/.zshrc
    state: absent
  when: sym.stat.islnk is defined and sym.stat.islnk == False

- name: Create a simbolic link from dotfiles to zsh
  become_user: "{{ user }}"
  tags: zsh
  ansible.builtin.shell: 
    cmd: "stow -t $HOME -d $HOME/dev/dotfiles zsh"

- name: Change zsh to default shell
  become: true
  tags: zsh
  ansible.builtin.shell:
    cmd: "chsh -s /bin/zsh {{ user }}"
